### PR TITLE
../taxcalc.js does no longer exists. Fixes #1.

### LINKED ISSUE #1: looks like this module does not work with VSF API version > 1.12.1
Problem is that https://github.com/vuestorefront/vue-storefront-api/tree/v1.12.2/src/lib does no longer have an `./src/lib/taxcalc.js` file
```
Trace: Error: Cannot find module '../../lib/taxcalc'                                                                           
Require stack:                                                                                                                 
- /home/pedro/work/super-shop/vue/vue-storefront-api/src/platform/opencart2/tax.js                                            
- /home/pedro/work/super-shop/vue/vue-storefront-api/src/platform/factory.ts                                                  
- /home/pedro/work/super-shop/vue/vue-storefront-api/src/api/order.ts                                                         
- /home/pedro/work/super-shop/vue/vue-storefront-api/src/api/index.ts                                                         
- /home/pedro/work/super-shop/vue/vue-storefront-api/src/index.ts                                                             
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)                                                
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)                                                           
    at Module.require (internal/modules/cjs/loader.js:1025:19)                                                                 
    at require (internal/modules/cjs/helpers.js:72:18)                                                                         
    at Object.<anonymous> (/home/pedro/work/super-shop/vue/vue-storefront-api/src/platform/opencart2/tax.js:2:1)              
    at Module._compile (internal/modules/cjs/loader.js:1137:30)                                                                
    at Module.m._compile (/home/pedro/work/super-shop/vue/vue-storefront-api/node_modules/ts-node/src/index.ts:473:23)        
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)                                                         
    at Object.require.extensions.<computed> [as .js] (/home/pedro/work/super-shop/vue/vue-storefront-api/node_modules/ts-node/
src/index.ts:476:12)                                                                                                           
    at Module.load (internal/modules/cjs/loader.js:985:32)                                                                     
    at Object.apiError (/home/pedro/work/super-shop/vue/vue-storefront-api/src/lib/util.js:97:12)                             
    at /home/pedro/work/super-shop/vue/vue-storefront-api/src/api/catalog.ts:192:9                                            
    at Generator.next (<anonymous>)                                                                                            
    at /home/pedro/work/super-shop/vue/vue-storefront-api/src/api/catalog.ts:8:71                                             
    at new Promise (<anonymous>)                                                                                               
    at __awaiter (/home/pedro/work/super-shop/vue/vue-storefront-api/src/api/catalog.ts:4:12)                                 
    at Request._callback (/home/pedro/work/super-shop/vue/vue-storefront-api/src/api/catalog.ts:141:39)                       
    at Request.self.callback (/home/pedro/work/super-shop/vue/vue-storefront-api/node_modules/request/request.js:185:22)      
    at Request.emit (events.js:315:20)                                                                                         
    at Request.<anonymous> (/home/pedro/work/super-shop/vue/vue-storefront-api/node_modules/request/request.js:1161:10)       
---                                                                                                                                

```

### PR DESCRIPTION
**Pull request by revington**
That import is fixed but I'm still getting my feet wet with VSF and I have no way to tell if I am breaking other stuff.

### CODE REVIEW

**Comment by themreza** [comment]
No worries :) I will keep this open until you figure out if your implementation works. 
Thanks for the PR!
